import type { Message, PartialMessage, ThreadChannel } from "discord.js";
import type { SessionContext, SessionManager } from "./session-manager";

export interface ImagePayload {
  type: "image";
  data: string;
  mimeType: string;
}

export interface TurnCheckpoint {
  /** Discord message ID for this user turn */
  discordMessageId: string;
  /** OMP session entry ID corresponding to this user message */
  entryId?: string;
  /** The user prompt text as entered on Discord */
  promptText: string;
  /** Epoch ms timestamp when the turn was initiated */
  timestamp: number;
  /** Discord message IDs of assistant responses/tool outputs created in this turn */
  assistantMessageIds?: string[];
}

export interface PendingRpcRequest {
  resolve: (value: unknown) => void;
  reject: (reason: unknown) => void;
  timer: Timer;
  command: string;
}

export interface RewindContext {
  sessionManager: SessionManager;
  isUserAllowed: (userId: string) => boolean;
  extractMessagePrompt: (
    session: SessionContext,
    message: Message,
  ) => Promise<{ text: string; images: ImagePayload[] }>;
  startTyping: (session: SessionContext, thread: ThreadChannel) => void;
  updateThreadNameFromPrompt?: (thread: ThreadChannel, prompt: string) => Promise<void>;
  sendRpc: (session: SessionContext, command: Record<string, unknown>) => void;
  abortTimeoutMs?: number;
}

/**
 * Record a user turn checkpoint in the session context.
 */
export function recordUserTurnCheckpoint(
  session: SessionContext,
  discordMessageId: string,
  promptText: string,
): TurnCheckpoint {
  if (!session.checkpoints) {
    session.checkpoints = [];
  }
  const existing = session.checkpoints.find((cp) => cp.discordMessageId === discordMessageId);
  if (existing) {
    existing.promptText = promptText;
    existing.timestamp = Date.now();
    return existing;
  }
  const cp: TurnCheckpoint = {
    discordMessageId,
    promptText,
    timestamp: Date.now(),
    assistantMessageIds: [],
  };
  session.checkpoints.push(cp);
  return cp;
}

/**
 * Record a Discord message ID generated by the bot into the active turn checkpoint.
 */
export function recordAssistantMessage(session: SessionContext, messageId: string): void {
  if (!session.checkpoints || session.checkpoints.length === 0) {
    return;
  }
  const current = session.checkpoints[session.checkpoints.length - 1];
  if (!current.assistantMessageIds) {
    current.assistantMessageIds = [];
  }
  if (!current.assistantMessageIds.includes(messageId)) {
    current.assistantMessageIds.push(messageId);
  }
}

/**
 * Synchronize session checkpoints with OMP branch messages list.
 * Matches checkpoints to branch messages by content to avoid desync from internal slash commands.
 */
export function syncCheckpointsWithBranchMessages(
  session: SessionContext,
  branchMessages: Array<{ entryId: string; text: string }>,
): void {
  if (!session.checkpoints || session.checkpoints.length === 0) {
    return;
  }

  let branchIdx = 0;
  const matchedCheckpoints: TurnCheckpoint[] = [];

  for (const cp of session.checkpoints) {
    let foundMatch = false;
    const cpText = cp.promptText.trim();

    while (branchIdx < branchMessages.length) {
      const msg = branchMessages[branchIdx++];
      const msgText = msg.text.trim();

      // Check if this branch message corresponds to this user checkpoint
      const isMatch =
        msgText === cpText ||
        (cpText.length > 0 && (msgText.endsWith(cpText) || msgText.includes(cpText))) ||
        (cpText.length === 0 && !msgText.startsWith("/"));

      if (isMatch) {
        cp.entryId = msg.entryId;
        matchedCheckpoints.push(cp);
        foundMatch = true;
        break;
      }
    }

    if (!foundMatch) {
      // Checkpoint not found in branch messages (e.g. transcript was rolled back or pruned)
      break;
    }
  }

  session.checkpoints = matchedCheckpoints;
}

/**
 * Find index of a checkpoint by Discord message ID.
 */
export function findCheckpointIndex(session: SessionContext, discordMessageId: string): number {
  if (!session.checkpoints) {
    return -1;
  }
  return session.checkpoints.findIndex((cp) => cp.discordMessageId === discordMessageId);
}

/**
 * Prune checkpoints from `fromIndex` onwards and return the pruned checkpoints.
 */
export function pruneCheckpoints(session: SessionContext, fromIndex: number): TurnCheckpoint[] {
  if (!session.checkpoints || fromIndex < 0 || fromIndex >= session.checkpoints.length) {
    return [];
  }
  const removed = session.checkpoints.slice(fromIndex);
  session.checkpoints = session.checkpoints.slice(0, fromIndex);
  return removed;
}

/**
 * Persist current session checkpoints into SessionStore metadata and synchronize session identifiers.
 */
export async function persistSessionCheckpoints(
  session: SessionContext,
  sessionManager: SessionManager,
): Promise<void> {
  await sessionManager.update(session.threadId, {
    sessionId: session.sessionId,
    sessionFile: session.sessionFile,
    metadata: {
      checkpoints: session.checkpoints,
    },
  }).catch((err) => {
    console.error(`Failed to persist checkpoints for thread ${ session.threadId }:`, err);
  });
}

/**
 * Delete assistant messages associated with pruned checkpoints using bulk delete where possible.
 */
export async function cleanupCheckpointsMessages(
  thread: ThreadChannel,
  checkpoints: TurnCheckpoint[],
): Promise<void> {
  const allMsgIds: string[] = [];
  for (const cp of checkpoints) {
    if (cp.assistantMessageIds && cp.assistantMessageIds.length > 0) {
      allMsgIds.push(...cp.assistantMessageIds);
    }
  }
  if (allMsgIds.length === 0) {
    return;
  }

  const uniqueIds = Array.from(new Set(allMsgIds));

  let bulkDeleted = false;
  if (typeof thread.bulkDelete === "function") {
    try {
      await thread.bulkDelete(uniqueIds);
      bulkDeleted = true;
    } catch {
      bulkDeleted = false;
    }
  }

  if (!bulkDeleted) {
    for (const msgId of uniqueIds) {
      try {
        const mgr = thread.messages;
        if (mgr && "delete" in mgr && typeof mgr.delete === "function") {
          await (mgr.delete as (id: string) => Promise<unknown>)(msgId).catch(() => {});
        } else {
          const msg =
            thread.messages.cache.get(msgId) ??
            (await thread.messages.fetch(msgId).catch(() => null));
          if (msg) {
            await msg.delete().catch(() => {});
          }
        }
      } catch {}
    }
  }
}

/**
 * Wait for an in-flight OMP turn to halt.
 */
export async function waitForTurnToStop(session: SessionContext, timeoutMs = 5000): Promise<boolean> {
  if (!session.isRunning) {
    return true;
  }
  const start = Date.now();
  while (session.isRunning && Date.now() - start < timeoutMs) {
    await Bun.sleep(50);
  }
  return !session.isRunning;
}

/**
 * Send an RPC command and await its response matching command.id.
 */
export function sendRpcRequest<T = unknown>(
  session: SessionContext,
  command: Record<string, unknown>,
  timeoutMs = 15000,
  sendRpcFn: (session: SessionContext, cmd: Record<string, unknown>) => void = (s, c) => {
    s.process.stdin.write(JSON.stringify(c) + "\n");
    s.process.stdin.flush();
  },
): Promise<T> {
  const { promise, resolve, reject } = Promise.withResolvers<T>();

  if (!session.pendingRpcRequests) {
    session.pendingRpcRequests = new Map();
  }
  const id = typeof command.id === "string" ? command.id : `req_${ Date.now() }_${ Math.random().toString(36).slice(2, 7) }`;
  const fullCommand: Record<string, unknown> = { ...command, id };
  const cmdName = typeof command.type === "string" ? command.type : typeof command.command === "string" ? command.command : "unknown";

  const timer = setTimeout(() => {
    session.pendingRpcRequests?.delete(id);
    reject(
      new Error(
        `RPC request '${ cmdName }' timed out after ${ timeoutMs }ms`,
      ),
    );
  }, timeoutMs);

  session.pendingRpcRequests.set(id, {
    resolve: resolve as (val: unknown) => void,
    reject,
    timer,
    command: cmdName,
  });
  try {
    sendRpcFn(session, fullCommand);
  } catch (err) {
    clearTimeout(timer);
    session.pendingRpcRequests.delete(id);
    reject(err);
  }
  return promise;
}

/**
 * Resolve a pending RPC request when a response frame is received.
 */
export function resolvePendingRpcResponse(
  session: SessionContext,
  event: Record<string, unknown>,
): boolean {
  const id = typeof event.id === "string" ? event.id : undefined;
  if (!id || !session.pendingRpcRequests?.has(id)) {
    return false;
  }
  const pending = session.pendingRpcRequests.get(id)!;
  clearTimeout(pending.timer);
  session.pendingRpcRequests.delete(id);

  if (event.success === false) {
    const errorMsg = typeof event.error === "string" ? event.error : "RPC command failed";
    pending.reject(new Error(errorMsg));
  } else {
    pending.resolve(event.data);
  }
  return true;
}

/**
 * Reject a pending RPC request on fatal error.
 */
export function rejectPendingRpcError(
  session: SessionContext,
  id: string | undefined,
  error: string,
): boolean {
  if (!id || !session.pendingRpcRequests?.has(id)) {
    return false;
  }
  const pending = session.pendingRpcRequests.get(id)!;
  clearTimeout(pending.timer);
  session.pendingRpcRequests.delete(id);
  pending.reject(new Error(error));
  return true;
}

/**
 * Handle Discord MessageUpdate event: rewind to checkpoint, update message, and submit new prompt.
 */
export async function handleMessageEditAsRewind(
  oldMessage: Message | PartialMessage,
  newMessage: Message | PartialMessage,
  context: RewindContext,
): Promise<boolean> {
  if (newMessage.author?.bot) {
    return false;
  }
  if (newMessage.author && !context.isUserAllowed(newMessage.author.id)) {
    return false;
  }

  const channel = newMessage.channel;
  if (!channel || !channel.isThread()) {
    return false;
  }

  const session = context.sessionManager.get(channel.id);
  if (!session) {
    return false;
  }

  if (session.isRewinding) {
    console.log(`[Rewind] Session in thread ${ channel.id } is already rewinding. Skipping duplicate event.`);
    return false;
  }

  const checkpoints = session.checkpoints || [];
  const cpIndex = checkpoints.findIndex((cp) => cp.discordMessageId === newMessage.id);
  if (cpIndex === -1) {
    // Not a tracked user turn
    return false;
  }

  const checkpoint = checkpoints[cpIndex];
  if (!newMessage.partial && newMessage.content.trim() === checkpoint.promptText) {
    return false;
  }

  session.isRewinding = true;

  try {
    const fullMessage = newMessage.partial
      ? await newMessage.fetch().catch(() => null)
      : (newMessage as Message);
    if (!fullMessage) {
      return false;
    }

    if (fullMessage.author.bot || !context.isUserAllowed(fullMessage.author.id)) {
      return false;
    }

    const newRawContent = fullMessage.content.trim();

    // If content is identical to tracked prompt, ignore (embed unfurl, pin, or no-op edit)
    if (newRawContent === checkpoint.promptText) {
      return false;
    }

    const { text, images } = await context.extractMessagePrompt(session, fullMessage);
    if (!text && images.length === 0) {
      return false;
    }

    await fullMessage.react("↩️").catch(() => {});
    const isPastTurn = cpIndex < checkpoints.length - 1;
    const statusMsg = await channel
      .send(
        isPastTurn
          ? `↩️ *Rewinding to turn #${ cpIndex + 1 } and re-running from edited prompt...*`
          : `↩️ *Updating turn #${ cpIndex + 1 } with edited prompt...*`,
      )
      .catch(() => null);

    // Abort if currently running
    if (session.isRunning) {
      context.sendRpc(session, { type: "abort" });
      const abortTimeout = context.abortTimeoutMs ?? 5000;
      const stopped = await waitForTurnToStop(session, abortTimeout);
      if (!stopped) {
        await statusMsg?.edit("⚠️ *Previous turn could not be halted in time. Please try again.*").catch(() => {});
        return false;
      }
      if (session.activePromptMsg) {
        await session.activePromptMsg.delete().catch(() => {});
        session.activePromptMsg = undefined;
      }
    }
    // Resolve OMP entryId
    let entryId = checkpoint.entryId;
    try {
      const branchData = await sendRpcRequest<{ messages: Array<{ entryId: string; text: string }> }>(
        session,
        { type: "get_branch_messages" },
        8000,
        context.sendRpc,
      );
      if (branchData?.messages) {
        syncCheckpointsWithBranchMessages(session, branchData.messages);
        const matchedCheckpoint = session.checkpoints?.find(
          (cp) => cp.discordMessageId === fullMessage.id,
        );
        if (matchedCheckpoint?.entryId) {
          entryId = matchedCheckpoint.entryId;
        }
      }
    } catch (err) {
      console.warn(`[Rewind] Error querying branch messages:`, err);
    }

    if (!entryId) {
      await statusMsg?.edit("⚠️ *Could not locate checkpoint in OMP transcript.*").catch(() => {});
      session.isRewinding = false;
      return false;
    }

    // Execute branch in OMP
    const branchRes = await sendRpcRequest<{ text: string; cancelled: boolean }>(
      session,
      { type: "branch", entryId },
      15000,
      context.sendRpc,
    );

    if (branchRes?.cancelled) {
      await statusMsg?.edit("⚠️ *Rewind was cancelled by OMP.*").catch(() => {});
      session.isRewinding = false;
      return false;
    }

    // Refresh state after branch
    try {
      const state = await sendRpcRequest<Record<string, unknown>>(
        session,
        { type: "get_state" },
        5000,
        context.sendRpc,
      );
      if (state) {
        if (typeof state.sessionId === "string") {
          session.sessionId = state.sessionId;
        }
        if (typeof state.sessionFile === "string") {
          session.sessionFile = state.sessionFile;
        }
      }
    } catch (err) {
      console.warn(`[Rewind] Error getting state after branch:`, err);
    }

    // Clean up orphaned assistant messages for rewound turns
    const removedCheckpoints = pruneCheckpoints(session, cpIndex);
    await cleanupCheckpointsMessages(channel, removedCheckpoints);

    // Delete transient status message
    if (statusMsg) {
      await statusMsg.delete().catch(() => {});
    }

    // If rewinding an older turn, leave a permanent note explaining the rollback to thread readers
    if (isPastTurn) {
      const preview = newRawContent.length > 80 ? `${ newRawContent.slice(0, 80) }...` : newRawContent;
      await channel.send(`↩️ *Rewound session to turn #${ cpIndex + 1 }:* "${ preview }"`).catch(() => {});
    }

    // Register new checkpoint for edited turn
    recordUserTurnCheckpoint(session, fullMessage.id, fullMessage.content.trim());
    await persistSessionCheckpoints(session, context.sessionManager);

    // Submit new prompt
    context.startTyping(session, channel);
    session.lastPrompt = newRawContent || "Attachment";
    if (context.updateThreadNameFromPrompt && cpIndex === 0) {
      await context.updateThreadNameFromPrompt(channel, session.lastPrompt);
    }

    context.sendRpc(session, {
      id: `prompt_${ Date.now() }`,
      type: "prompt",
      message: text,
      ...(images.length > 0 ? { images } : {}),
    });

    return true;
  } catch (err) {
    console.error(`[Rewind] Failed to execute edit-as-a-rewind:`, err);
    await channel
      .send(`⚠️ *Failed to rewind checkpoint: ${ err instanceof Error ? err.message : String(err) }*`)
      .catch(() => {});
    return false;
  } finally {
    session.isRewinding = false;
  }
}
