import { ActionRowBuilder, ButtonBuilder, ButtonStyle } from "discord.js";

export type QuickAction = "undo" | "compact" | "abort" | "status";

export interface ParsedQuickAction {
  action: QuickAction;
  threadId: string;
}

export type ReactionShortcut = "abort" | "undo";

export type ThreadStatus = "running" | "idle" | "error" | "pending";

const STATUS_EMOJI: Record<ThreadStatus, string> = {
  running: "🟡",
  idle: "🟢",
  error: "🔴",
  pending: "⏸️",
};

const STATUS_PREFIX = /^(?:🟡|🟢|🔴|⏸️)\s*/u;

/** Build the four-button action bar attached to completed assistant messages. */
export function buildQuickActionRow(threadId: string): ActionRowBuilder<ButtonBuilder> {
  return new ActionRowBuilder<ButtonBuilder>().addComponents(
    new ButtonBuilder()
      .setCustomId(`action_undo_${threadId}`)
      .setEmoji("🔄")
      .setLabel("Undo")
      .setStyle(ButtonStyle.Secondary),
    new ButtonBuilder()
      .setCustomId(`action_compact_${threadId}`)
      .setEmoji("🗜️")
      .setLabel("Compact")
      .setStyle(ButtonStyle.Primary),
    new ButtonBuilder()
      .setCustomId(`action_abort_${threadId}`)
      .setEmoji("⏹️")
      .setLabel("Abort")
      .setStyle(ButtonStyle.Danger),
    new ButtonBuilder()
      .setCustomId(`action_status_${threadId}`)
      .setEmoji("📊")
      .setLabel("Status")
      .setStyle(ButtonStyle.Success),
  );
}

/** Parse only action IDs generated by buildQuickActionRow. */
export function parseQuickActionId(customId: string): ParsedQuickAction | null {
  const match = /^action_(undo|compact|abort|status)_(.+)$/u.exec(customId);
  if (!match || !match[2]) return null;
  return { action: match[1] as QuickAction, threadId: match[2] };
}

/** Convert Discord emoji names/unicode values into the supported reaction shortcut. */
export function parseReactionShortcut(emoji: string | null | undefined): ReactionShortcut | null {
  if (!emoji) return null;
  if (emoji === "🔄" || emoji === "arrows_counterclockwise") return "undo";
  if (emoji === "🛑" || emoji === "❌" || emoji === "octagonal_sign" || emoji === "x") return "abort";
  return null;
}

export function getThreadStatusEmoji(status: ThreadStatus): string {
  return STATUS_EMOJI[status];
}

/** Return true for names that have not yet been customized for a prompt. */
export function isDefaultThreadName(name: string): boolean {
  const clean = name.trim().replace(STATUS_PREFIX, "").trim();
  return /^omp-session-[^\s]+$/iu.test(clean);
}

/** Extract a compact, human-readable topic and optional OMX skill label from a prompt. */
export function extractPromptTopic(prompt: string): { topic: string; skill?: string } {
  const normalized = prompt.replace(/\s+/gu, " ").trim();
  const skillMatch = /^\$(\w[\w-]*)\s*(.*)$/u.exec(normalized);
  if (skillMatch) {
    return {
      skill: skillMatch[1],
      topic: (skillMatch[2] || "session").trim(),
    };
  }

  const slashSkillMatch = /^\/skill\s+(\w[\w-]*)\s*(.*)$/iu.exec(normalized);
  if (slashSkillMatch) {
    return {
      skill: slashSkillMatch[1],
      topic: (slashSkillMatch[2] || "session").trim(),
    };
  }

  return { topic: normalized || "session" };
}

/**
 * Build a prompt-derived name only while the thread still has its generated default name.
 * Discord thread names are capped at 100 characters.
 */
export function buildDynamicThreadName(prompt: string, currentName: string, status: ThreadStatus = "running"): string {
  if (!isDefaultThreadName(currentName)) return currentName;
  const { topic, skill } = extractPromptTopic(prompt);
  const label = skill ? `[${skill}] ` : "";
  const prefix = getThreadStatusEmoji(status);
  const combined = `${prefix} ${label}${topic}`.trim();
  return combined.length <= 100 ? combined : `${combined.slice(0, 97)}...`;
}

/** Replace a prior status prefix while preserving the user's thread topic. */
export function updateThreadStatusName(currentName: string, status: ThreadStatus): string {
  const topic = currentName.trim().replace(STATUS_PREFIX, "").trim() || "OMP session";
  return `${getThreadStatusEmoji(status)} ${topic}`.slice(0, 100);
}
